// source: storage_message.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global = Function('return this')();

var memory_message_pb = require('./memory_message_pb.js');
goog.object.extend(proto, memory_message_pb);
goog.exportSymbol('proto.Storage', null, global);
goog.exportSymbol('proto.Storage.Driver', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.Storage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.Storage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.Storage.displayName = 'proto.Storage';
}



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.Storage.prototype.toObject = function(opt_includeInstance) {
  return proto.Storage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.Storage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Storage.toObject = function(includeInstance, msg) {
  var f, obj = {
    driver: jspb.Message.getFieldWithDefault(msg, 1, 0),
    memory: (f = msg.getMemory()) && memory_message_pb.Memory.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.Storage}
 */
proto.Storage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.Storage;
  return proto.Storage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.Storage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.Storage}
 */
proto.Storage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.Storage.Driver} */ (reader.readEnum());
      msg.setDriver(value);
      break;
    case 2:
      var value = new memory_message_pb.Memory;
      reader.readMessage(value,memory_message_pb.Memory.deserializeBinaryFromReader);
      msg.setMemory(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.Storage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.Storage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.Storage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.Storage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDriver();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getMemory();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      memory_message_pb.Memory.serializeBinaryToWriter
    );
  }
};


/**
 * @enum {number}
 */
proto.Storage.Driver = {
  UNKNOWN: 0,
  HDD: 1,
  SSD: 2
};

/**
 * optional Driver driver = 1;
 * @return {!proto.Storage.Driver}
 */
proto.Storage.prototype.getDriver = function() {
  return /** @type {!proto.Storage.Driver} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.Storage.Driver} value
 * @return {!proto.Storage} returns this
 */
proto.Storage.prototype.setDriver = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional Memory memory = 2;
 * @return {?proto.Memory}
 */
proto.Storage.prototype.getMemory = function() {
  return /** @type{?proto.Memory} */ (
    jspb.Message.getWrapperField(this, memory_message_pb.Memory, 2));
};


/**
 * @param {?proto.Memory|undefined} value
 * @return {!proto.Storage} returns this
*/
proto.Storage.prototype.setMemory = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.Storage} returns this
 */
proto.Storage.prototype.clearMemory = function() {
  return this.setMemory(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.Storage.prototype.hasMemory = function() {
  return jspb.Message.getField(this, 2) != null;
};


goog.object.extend(exports, proto);
